#ifndef CONFIG_INCLUDE_H
#define CONFIG_INCLUDE_H

#define PROJECT_NAME "mission"
#define PROJECT_VERSION "0.0.1"
#define PROJECT_VERSION_MAJOR "0"
#define PROJECT_VERSION_MINOR "0"
#define PROJECT_VERSION_PATCH "1"

#endif  // CONFIG_INCLUDE_H
